name: Downgrade

on:
    pull_request:
        paths-ignore:
            - "LICENSE.md"
            - "README.md"
            - ".github/workflows/CompatHelper.yml"
            - ".github/workflows/TagBot.yml"
            - "docs/**"
    workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    downgrade_test:
        name: Downgrade ${{ matrix.os }} on ${{ matrix.julia-version }} - ${{ github.event_name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                julia-version: ["1.10", "1.11", "1.12"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v6
            - uses: julia-actions/setup-julia@v2
              with:
                  version: ${{ matrix.julia-version }}
            - uses: julia-actions/cache@v2
            - uses: julia-actions/julia-downgrade-compat@v2
              with:
                  skip: LinearAlgebra, Random, Statistics, SparseArrays, Test, Enzyme, EnzymeCore, Mooncake, LuxCore, DifferentiationInterface, ForwardDiff, FiniteDifferences, HaltonSequences, SafeTestsets, ChainRulesCore, RadialBasisFunctions
                  projects: ., test
                  mode: deps
            - uses: julia-actions/julia-buildpkg@v1
              env:
                  PYTHON: ""
            - name: Run tests
              run: |
                  julia --project=test --color=yes -e '
                    import Pkg
                    Pkg.develop(Pkg.PackageSpec(path=pwd()))
                    Pkg.instantiate()
                    Pkg.status(; mode=Pkg.PKGMODE_MANIFEST)
                    include("test/runtests.jl")
                  '
              env:
                  PYTHON: ""
